services:
  web:
    entrypoint: ['/usr/src/app/entrypoint.sh']
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - my_network


  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sohump
      - POSTGRES_PASSWORD=sohump
      - POSTGRES_DB=dev_db
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
